awaid/urls.py

from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('siteweb.urls', namespace="main")),
    path('search/', include('search.urls', namespace="search")),
    # path('', RedirectView.as_view(url='/awaid/', permanent=True)),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'siteweb.views.error_404'

search/urls.py
from django.urls import path
from search.views import searchView


app_name = "search"
urlpatterns = [
    path('', searchView, name='search'),
]

siteweb/urls.py
from django.urls import path
from .views import (
    CategoryToolListView, 
    ToolCategoryDetailView, 
    ToolTypeDetailView, 
    SpecificToolDetailView,
    ToolGroupDetailView,
    brand_list,
    ImageEmailProList,
    ImageEmailProDetail,
    catalog_list
    )


app_name = "main"
urlpatterns = [
    path('', CategoryToolListView.as_view(), name='home'),
    path('categories/<int:pk>/<slug:slug>', 
        ToolCategoryDetailView.as_view(), 
        name="category-detail"
    ),

    path('tooltypes/<int:pk>/<slug:slug>', 
        ToolTypeDetailView.as_view(), 
        name="tooltype"
    ),

    path('toolgroups/<int:pk>/<slug:slug>', 
        ToolGroupDetailView.as_view(), 
        name="toolgroup"
    ),

    path('tools/<int:pk>-<slug:slug>',
        SpecificToolDetailView.as_view(), 
        name="specifictool"
    ),

    path('brands/', brand_list, name="brands"),
    path('emailpro/', ImageEmailProList.as_view(), name="imagelist"),
    path('emailpro/image/<int:pk>/', ImageEmailProDetail.as_view(), name="imagepro"),

    path('catalogs/', catalog_list, name="catalogs"),

]

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="fr-FR">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <meta name="author" content="SmartDev, smartdev, smartdevci">
  <meta name="keywords" content="SmartDev, smartdev, smartdevci">
    <title>
        {% block title %} AWAID | Fournisseur d'Equipements  industriels {% endblock %}
    </title>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/metro-all.min.css' %}">
</head>

<body>
    {% block navbar %}
        {% include 'includes/navbar.html' %}
    {% endblock %}

    <div id="home">
        <!-- SLIDER -->
        {% block slider %}{% endblock %}
        <!--/#about-slider-->
    </div>

    {% block section-about %}
        <div class="container">
            {% block about %}{% endblock %}
        </div>

        <div class="container">
            {% block distribution %}{% endblock %}
        </div>
    {% endblock %}

    {% block partenaire %} {% endblock %}

    {% block contact %}{% endblock %}
        <!--/#contact-page-->

    {% block footer %}
    <footer id="footer" class="bg-darkRed p-10 m-0">
        <div class="container">
            <div class="row">
                <div class="cell-12">
                    <div class="text-center">
                        <span class="mr-5" data-role="hint" data-hint-text="Remonter">
                            <a href="#home" title ><i class="mif-arrow-up mif-3x"></i></a>
                        </span>
                        <span class="mr-5"><a href="#"><i class="mif-facebook2 mif-3x"></i></a></span>
                        <span class="mr-5"><a href="#"><i class="mif-twitter mif-3x"></i></a></span>
                    </div>
                </div>
            </div>
          <div class="row">
            <div class="cell-md-12">
                <div class="text-center">
                    <p class="fg-white">2020 &copy; AWAID - Tous droits reservés.</p>
                    <p class="fg-white">Design by <a href="smartdevci.com"><strong>SmartDev</strong></a></p>
                </div>
            </div>
          </div>
        </div>
      </footer>
  <!--/#footer-->
    {% endblock %}


  <script src="{% static 'js/metro.min.js' %}"></script>
</body>
</html>

templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="SmartDev, smartdev, smartdevci">
    <meta name="keywords" content="SmartDev, smartdev, smartdevci">
    <title>
        {% block title %} AWAID | Fournisseur d'Equipements  industriels !{% endblock %}
    </title>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/metro-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        div.default--height {
            min-height: 400px;
        }
    </style>
</head>
<body>
    <!-- NAME & CONTACT -->
    <div class="row visible-sm">
        <div class="cell-12 bg-red fg-white">
            <div class="container">
                <div class="d-flex flex-justify-start">
                    <div class="d-inline-md text-leader2"><span class="text-bold">AWAID SARL</span>
                        <span class="text-secondary" style="position: relative; top: -2px; left: 10px;">La fourniture industrielle autrement !</span>
                    </div>
                    <div class="mr-auto"></div>
                    <div class="d-inline">
                        <span class="mif-phone"></span>
                        (+225) 27 21 59 59 10 - 27 21 00 21 11 - 05 46 80 80 31
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- LOGO GIF & SEARCH FIELD -->
    <div class="row">
        <div class="cell-md-8 offset-md-2">
            <div class="row my-1">
                <div class="container">
                    <div class="d-flex flex-justify-center flex-align-center">
                        <div class="d-inline img-container" style="width: 20%;">
                            <a href="{% url 'main:home' %}">
                                <img src="{% static 'images/logo.gif' %}" 
                                    alt="logo" 
                                    class="image"
                                >
                            </a>
                        </div>
                        <!-- <div class="mr-auto"></div> -->
                        <div class="d-inline-flex ml-20">
                            <form action="{% url 'search:search' %}" method="get">
                                <input type="text" 
                                    class="put-right w-200"
                                    data-role="input"
                                    data-search-button="true"
                                    placeholder="Rechercher un produit"
                                    name="query"
                                >
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div data-role="appbar"
        data-expand-point="md"
        class="bg-lightRed d-flex flex-justify-center"
        style="background-color: transparent;"
        >
        <ul class="app-bar-menu" id="navbar">
                {% for category in categories %}
                    <li class="menu-item">
                        <a href="{{ category.get_absolute_url }}" class="link-menu">
                            {{ category.category_name | upper }}
                        </a>
                        <a href="#" class="dropdown-toggle no-visible" style="display: none"></a>
                        <ul class="d-menu" data-role="dropdown">
                            {% for tool_type in category.toolcategories.all %}
                                <li>
                                    <a href="{{ tool_type.get_absolute_url }}">
                                        {{ tool_type.tooltype_description | upper }}
                                    </a>
                                </li>
                                <li class="divider bg-lightGray"></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}

                <li class="menu-item">
                    <a href="{% url 'main:catalogs' %}" class="link-menu px-2 text-upper">
                        Catalogues
                    </a>
                </li>
                <li class="menu-item">
                    <a href="{% url 'main:brands' %}" class="link-menu px-2 text-upper">
                        Nos marques
                    </a>
                </li>
        </ul>
    </div> 

    <div class="row">
        {% block breadcrumbs %}
        {% endblock breadcrumbs %}
    </div>

    <div class="default--height">
        {% block body %}
            <div id="home">
                <!-- SLIDER -->
                {% block slider %}{% endblock slider %}
                <!--/#about-slider-->
            </div>

            <div>
                {% block categoryDetail %}
                {% endblock categoryDetail %}
            </div>

        {% endblock body %}
    </div>

    <footer class="bg-grayBlue">
        <div class="container">
            <div class="row container">
                <div class="cell-md-9">
                    <div class="row">
                        <div class="cell-sm-12 cell-md-4 d-flex flex-justify-start">
                            <address class="text-leader2 fg-white mt-3" >
                                République de Côte d'Ivoire<br>
                                <div style="line-height: 1.6;"></div>
                                
                                <span class="mif-location fg-red"></span>
                                <em class="ml-2">Abidjan, Koumassi Nord-Est, non loin de l'école Concordia</em><br>
                                <span class="mif-phone mr-2 fg-red" style="color: #eb253f;"></span>
                                <span>(+225) 27 21 59 59 10</span><br>
                                <span class="ml-8">(+225) 27 21 00 21 11</span>
                                <br>
                                <span class="mif-mobile mr-2 fg-red" style="color: #f5deb3;"></span>
                                (+225) 05 46 80 80 31<br>
                                <span class="mif-mail mr-2 fg-red" style="color: #f5deb3;"></span>
                                <a href="mailto:info@awaid-ci.com" class="fg-white">info@awaid-ci.com</a>
                            </address>
                        </div>
                        <div class="cell-sm-12 cell-md-4 my-0 py-0">
                            <div class="row">
                                <ul class="cell-12 unstyled">
                                    {% for category in categories %}
                                        <li class="text-upper" style="list-style-type: none">
                                            <span class="mif-chevron-right"></span>
                                            <a class="fg-white" href="{{ category.get_absolute_url }}">{{ category }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="cell-sm-12 cell-md-4 flex-justify">
                            <div class="row fg-white">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d516.4788788130941!2d-3.946459133393579!3d5.311759052967034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfc1edccc4a485f9%3A0xa629f944a2f58172!2sEcole%20Primaire%20Priv%C3%A9e%20Concordia!5e0!3m2!1sfr!2sci!4v1696783777321!5m2!1sfr!2sci"
                                        width="600"
                                        height="220"
                                        style="border:0;"
                                        allowfullscreen=""
                                        loading="lazy"
                                        referrerpolicy="no-referrer-when-downgrade"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cell-md-3 fg-white text-center mt-3 text-leader2"
                    style="font-size: 16px; position: relative; left: 50px" >
                    {% now 'Y' as current_year %}
                    <div class="mb-5">2020 - {{ current_year }} &copy; AWAID <br>Tous droits reservés</div>
                    <div class="img-container">
                        <div class="mb-2 fg- text-bold" style="color: #f5deb3;">Conception & <br>Développement</div>
                        <a href="http://www.smartdevci.com" target="_blank">
                            <img src="{% static 'images/smartdev.png' %}" alt="logo" class="w-50 image">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/metro.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>